//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace доставка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Order_Employee = new HashSet<Order_Employee>();
        }
    
        public int ID_Employee { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Berthday { get; set; }
        public string Bank_card { get; set; }
        public int ID_Position { get; set; }
        public int ID_Branch { get; set; }

        public string FullName
        {
            get
            {
                if (Patronymic == null)
                    return $"{LName.Trim()} {FName[0]}.";
                else
                    return $"{LName.Trim()} {FName[0]}. {Patronymic[0]}.";

            }
        }

        public virtual Branch Branch { get; set; }
        public virtual Job_Position Job_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Employee> Order_Employee { get; set; }
    }
}
