//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace доставка
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Employee = new HashSet<Order_Employee>();
            this.OrderDish = new HashSet<OrderDish>();
        }
    
        public int ID_Order { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Client { get; set; }
        public int ID_PaymentMethod { get; set; }
        public int ID_Status { get; set; }
        public decimal Price { get; set; }
        public int ID_Branch { get; set; }

        public decimal NewPrice
        {
            get
            {
                Price = OrderDish.Where(n => n.ID_Order == ID_Order).Sum(n => n.price);
                return Price - (((decimal)Client.Discount / 100) * Price);
            }
        }

        public virtual Branch Branch { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Employee> Order_Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDish> OrderDish { get; set; }
    }
}
