//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace доставка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Employee
    {
        public int ID { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Order { get; set; }

        public string FullName
        {
            get
            {
                return Employee.FullName;
            }
        }

        public string Job
        {
            get
            {
                return Employee.Job_Position.Name;
            }
        }

        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
    }
}
