//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace доставка
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDish
    {
        public int ID { get; set; }
        public int ID_OrderDish { get; set; }
        public int ID_Order { get; set; }
        public int Count { get; set; }

        public decimal price
        {
            get
            {
                return Menu.Price * Count;
            }
        }

        public string dishName
        {
            get
            {
                return Menu.Name;
            }
        }

        public DateTime date
        {
            get
            {
                return Order.Date;
            }
        }

        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
